// These const strings should be consistent with backend sirius.realdata.constants
const DATA_SOURCE_GENOME = 'GRCh38_gff';
const DATA_SOURCE_GWAS = 'GWAS Catalog';
const DATA_SOURCE_CLINVAR = 'ClinVar';
const DATA_SOURCE_DBSNP = 'dbSNP';
const DATA_SOURCE_ENCODE = 'ENCODE';
const DATA_SOURCE_FASTA = 'RefSeq';
const DATA_SOURCE_EFO = 'EFO';
const DATA_SOURCE_ENCODEbigwig = 'ENCODEbigwig';
const DATA_SOURCE_ExAC = 'ExAC';
const DATA_SOURCE_TCGA = 'TCGA';
const DATA_SOURCE_ENSEMBL = 'ENSEMBL';
const DATA_SOURCE_GTEX = 'GTEx';

const CHROMOSOME_NAMES: Array<string> = [];
for (let i = 1; i < 23; i++) {
  CHROMOSOME_NAMES.push(`chr${i}`);
}

CHROMOSOME_NAMES.push('chrX');
CHROMOSOME_NAMES.push('chrY');

const DATA_SOURCES = [
  DATA_SOURCE_GENOME,
  DATA_SOURCE_GWAS,
  DATA_SOURCE_CLINVAR,
  DATA_SOURCE_DBSNP,
  DATA_SOURCE_ENCODE,
  DATA_SOURCE_FASTA,
  DATA_SOURCE_EFO,
  DATA_SOURCE_ENCODEbigwig,
  DATA_SOURCE_ExAC,
  DATA_SOURCE_TCGA,
  DATA_SOURCE_ENSEMBL,
  DATA_SOURCE_GTEX
];

const FILE_TYPE_23andMe = '23andme';
const FILE_TYPE_VCF = 'vcf';

export {
  CHROMOSOME_NAMES,
  DATA_SOURCE_GENOME,
  DATA_SOURCE_GWAS,
  DATA_SOURCE_CLINVAR,
  DATA_SOURCE_DBSNP,
  DATA_SOURCE_ENCODE,
  DATA_SOURCE_FASTA,
  DATA_SOURCE_EFO,
  DATA_SOURCE_ENCODEbigwig,
  DATA_SOURCE_ExAC,
  DATA_SOURCE_TCGA,
  DATA_SOURCE_ENSEMBL,
  DATA_SOURCE_GTEX,
  DATA_SOURCES,
  FILE_TYPE_23andMe,
  FILE_TYPE_VCF,
};
