# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: yudongdev/node-gcloud:8.9.4

    working_directory: ~/VALIS-frontend

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: npm-install
          command: |
            NODE_ENV=development npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: prep-gcloud
          command: ./tools/prep_gcloud.sh
      - run:
          name: webpack
          command: NODE_ENV=development npm run deploy
      - run:
          name: trigger-roll-out
          command: ./tools/trigger_sirius_deployment.sh
      - store_artifacts:
          path: dist

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
        filters:
          branches:
            only: master

