# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: yudongdev/node-gcloud:8.9.4
    working_directory: ~/VALIS-frontend
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: |
            NODE_ENV=development npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - store_artifacts:
          path: dist
  test:
    docker:
      - image: yudongdev/node-gcloud:8.9.4
    working_directory: ~/VALIS-frontend
    steps:
      - checkout
      - run:
          name: test build
          # we need to add some tests here
          command: echo "Testing"
  deploy:
    docker:
      - image: yudongdev/node-gcloud:8.9.4
    working_directory: ~/VALIS-frontend
    steps:
      - checkout
      - run:
          name: prep-gcloud
          command: ./tools/prep_gcloud.sh
      - run:
          name: webpack
          command: NODE_ENV=development npm run deploy
      - run:
          name: trigger-roll-out
          command: ./tools/trigger_sirius_deployment.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches: 
              only:
                master

