# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: yudongdev/node-gcloud:8.9.4
    working_directory: ~/VALIS-frontend
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: |
            NODE_ENV=development npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      # we need to add some tests here
      - run:
          name: Run tests
          command: echo "Testing"
      - deploy:
          name: Deploy on Google Cloud
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ ! -z "$GCLOUD_SERVICE_KEY" ]; then
              ./tools/prep_gcloud.sh
              NODE_ENV=development npm run deploy
              ./tools/trigger_sirius_deployment.sh
            fi
      - store_artifacts:
          path: dist

